# .sqa/config.yml - jenkins-pipeline-library configuration file

# generic configuration: workspace, agents
config:
  project_repos:
    bench_api:
      repo: 'https://github.com/EOSC-synergy/bench_event_api.git'
      branch: jenkins

#   credentials:
#     - id: my-dockerhub-token
#       username_var: JPL_DOCKERUSER
#       password_var: JPL_DOCKERPASS

# environment:
#   JPL_DOCKERPUSH: "processing"
#   JPL_IGNOREFAILURES: "defined"

sqa_criteria:
  qc_style:
    repos:
      bench_api:
        container: processing
        tox:
          tox_file: /bench_event_api-testing/tox.ini
          testenv:
            - pep8
  qc_security:
    repos:
      bench_api:
        container: processing
        tox:
          tox_file: /bench_event_api-testing/tox.ini
          testenv:
            - bandit
  qc_coverage:
    repos:
      bench_api:
        container: processing
        tox:
          tox_file: /bench_event_api-testing/tox.ini
          testenv: 
            - cover
            - cobertura

#environment:
 # GIT_COMMITTER_NAME: javi-gv94
  #GIT_COMMITTER_EMAIL: javier.garrayo@hotmail.com
  #LANG: C.UTF-8

#timeout: 600
